version: '3'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: jitsi/etherpad:latest
        restart: ${RESTART_POLICY}
        environment:
            - TITLE="${ETHERPAD_TITLE}"
            - DEFAULT_PAD_TEXT="${ETHERPAD_DEFAULT_PAD_TEXT}"
            - SKIN_NAME="${ETHERPAD_SKIN_NAME}"
            - SKIN_VARIANTS="${ETHERPAD_SKIN_VARIANTS}"
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
